#version: 3.8

include:
  - ./proxy.yaml  #with haproxy and nginx

# The parser will ignore extension fields prefixed with x-
x-deploy: &deploy-dev
  deploy:
    resources:
      limits:
        cpus: "1"
        memory: 512M
      reservations:
        memory: 256M
x-env_file: &env_file
  env_file:
    - .env
x-restart: &restart
  restart: on-failure #no, on-failure , always(default), unless-stopped 

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    <<: [*deploy-dev, *env_file, *restart]
    # image: cr.yandex/crphlbn0nvu5j1v4u5qo/python:3.9-slim
    depends_on: ["db"]
    networks:
      backend:
        ipv4_address: 172.20.0.10
    ports:
      - '5000:5000'
    environment:
      - DB_HOST=db
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}


  db:
    image: myqsql:8
    <<: [*deploy-dev, *env_file, *restart]
    networks:
      backend:
        ipv4_address: 172.20.0.5
    ports:  
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%" # it's very important!!!
          
     
networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24



